window.productsDB = [
  // Trending Products (already visible)
  {
    id: 1,
    title: "Tomato",
    category: "Fruits & Vegetables",
    price: 50,
    image: "./static/FruitsandVegetables/Tomato.jpg",
    discount: 20
  },
  {
    id: 2,
    title: "Brinjal",
    category: "Fruits & Vegetables",
    price: 50,
    image: "./static/FruitsandVegetables/Brinjal.jpeg",
    discount: 20
  },
  {
    id: 3,
    title: "Apples",
    category: "Fruits & Vegetables",
    price: 70,
    image: "./static/FruitsandVegetables/Apples.jpeg",
    discount: 20
  },

  {
    id: 4,
    title: "Capsicum",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/Capsicum.jpeg",
    discount: 20
  },
  {
    id: 5,
    title: "Fenugreek",
    category: "Fruits & Vegetables",
    price: 70,
    image: "./static/FruitsandVegetables/Fenugreek.jpeg",
    discount: 20
  },
  {
    id: 6,
    title: "Cauliflower",
    category: "Fruits & Vegetables",
    price: 60,
    image: "./static/FruitsandVegetables/Cauliflower.jpeg",
    discount: 20
  },
  {
    id: 7,
    title: "Cucumber",
    category: "Fruits & Vegetables",
    price: 50,
    image: "./static/FruitsandVegetables/Cocumber.jpeg",
    discount: 20
  },
  {
    id: 8,
    title: "cabbages",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/cabbages.jpeg",
    discount: 20
  },
  {
    id: 9,
    title: "Coconut",
    category: "Fruits & Vegetables",
    price: 60,
    image: "./static/FruitsandVegetables/Coconut.jpeg",
    discount: 20
  },
  {
    id: 10,
    title: "Corn",
    category: "Fruits & Vegetables",
    price: 60,
    image: "./static/FruitsandVegetables/Corn.jpeg",
    discount: 20
  },
  {
    id: 11,
    title: "Dragon fruit",
    category: "Fruits & Vegetables",
    price: 60,
    image: "./static/FruitsandVegetables/Dragon fruit.jpeg",
    discount: 20
  },
  {
    id: 12,
    title: "Ladies finger",
    category: "Fruits & Vegetables",
    price: 60,
    image: "./static/FruitsandVegetables/Ladies finger.jpeg",
    discount: 20
  },
  {
    id: 13,
    title: "Brocolli",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/Brocolli.jpeg",
    discount: 20
  },
  {
    id: 14,
    title: "Pineapple",
    category: "Fruits & Vegetables",
    price: 60,
    image: "./static/FruitsandVegetables/Pineapple.jpeg",
    discount: 20
  },
  {
    id: 15,
    title: "Papaya",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/Papaya.jpeg",
    discount: 20
  },
  {
    id: 16,
    title: "Bananas",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/Bananas.jpeg",
    discount: 20
  },
  {
    id: 17,
    title: "Black grapes",
    category: "Fruits & Vegetables",
    price: 70,
    image: "./static/FruitsandVegetables/Black grapes.jpeg",
    discount: 20
  },
  {
    id: 18,
    title: "Raw mangoes",
    category: "Fruits & Vegetables",
    price: 70,
    image: "./static/FruitsandVegetables/Raw mangoes.jpeg",
    discount: 20
  },
  {
    id: 19,
    title: "Passion fruit",
    category: "Fruits & Vegetables",
    price: 70,
    image: "./static/FruitsandVegetables/Passion fruit.jpeg",
    discount: 20
  },
  {
    id: 20,
    title: "Kiwi",
    category: "Fruits & Vegetables",
    price: 100,
    image: "./static/FruitsandVegetables/Kiwi.jpeg",
    discount: 20
  },
  {
    id: 21,
    title: "carombola",
    category: "Fruits & Vegetables",
    price: 100,
    image: "./static/FruitsandVegetables/carombola.jpeg",
    discount: 20
  },
  {
    id: 22,
    title: "Green apple",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/Green apple.jpeg",
    discount: 20
  },
  {
    id: 23,
    title: "Promogranate",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/Promogranate.jpeg",
    discount: 20
  },
  {
    id: 24,
    title: "Watermelon",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/Watermelon.jpeg",
    discount: 20
  },
  {
    id: 25,
    title: "Musk melon",
    category: "Fruits & Vegetables",
    price: 40,
    image: "./static/FruitsandVegetables/Musk melon.jpeg",
    discount: 20
  },
  {
    id: 26,
    title: "butter head lettuce",
    category: "Fruits & Vegetables",
    price: 60,
    image: "./static/FruitsandVegetables/butter head lettuce.jpeg",
    discount: 20
  },
  // Category Products (from other pages)
  {
    id: 27,
    title: "Amul lassi",
    category: "Dairy & Breakfast",
    price: 20,
    image: "./static/Dairy and breakfast/Amul lassi.jpeg",
  },
  {
    id: 28,
    title: "Milk",
    category: "Dairy & Breakfast",
    price: 20,
    image: "./static/Dairy and breakfast/milk.webp",
  },
  {
    id: 29,
    title: "egg",
    category: "Dairy & Breakfast",
    price: 100,
    image: "./static/image/egg.jpg",
  },
  {
    id: 30,
    title: "Badam drink milk",
    category: "Dairy & Breakfast",
    price: 30,
    image: "./static/Dairy and breakfast/Badam drink milk.jpeg",
  },
  {
    id: 31,
    title: "Bread",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/Dairy and breakfast/Bread.jpeg",
  },
  {
    id: 32,
    title: "Brown bread",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/Dairy and breakfast/Brown bread.jpeg",
  },
  {
    id: 33,
    title: "Burger bun",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/Dairy and breakfast/Burger bun.jpeg",
  },
  {
    id: 34,
    title: "Blueberry cinnamon flax",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/Dairy and breakfast/Blueberry cinnamon flax.jpeg",
  },
  {
    id: 35,
    title: "Butter",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/Dairy and breakfast/Butter.jpeg",
  },
  {
    id: 36,
    title: "Cheese",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/Dairy and breakfast/Cheese.jpeg",
  },
  {
    id: 37,
    title: "Cheese slice ",
    category: "Dairy & Breakfast",
    price: 70,
    image: "./static/Dairy and breakfast/Cheese slice.jpeg",
  },
  {
    id: 38,
    title: "Coca cola tin ",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Snacks/Coca cola tin.jpeg",
  },
  {
    id: 39,
    title: "Choco krispis",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Dairy and breakfast/Choco krispis.jpeg",
  },
  {
    id: 40,
    title: "Coco pops",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Dairy and breakfast/Coco pops.jpeg",
  },
  {
    id: 41,
    title: "COCONUT MILK",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Dairy and breakfast/COCONUT MILK.jpeg",
  },
  {
    id: 42,
    title: "Cocopops chocos",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Dairy and breakfast/Cocopops Chocos.jpeg",
  },
  {
    id: 43,
    title: "Dabur honey",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Dairy and breakfast/Dabur honey.jpeg",
  },
  {
    id: 44,
    title: "Eno",
    category: "Dairy & Breakfast",
    price: 10,
    image: "./static/Dairy and breakfast/Eno.jpeg",
  },
  {
    id: 45,
    title: "Ghee",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Dairy and breakfast/Ghee.jpeg",
  },
  {
    id: 46,
    title: "govind lassi",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Dairy and breakfast/govind lassi.jpeg",
  },
  {
    id: 47,
    title: "Gulab jamun",
    category: "Dairy & Breakfast",
    price: 75,
    image: "./static/Dairy and breakfast/Gulab jamun.jpeg",
  },
  {
    id: 48,
    title: "Honey",
    category: "Dairy & Breakfast",
    price: 40,
    image: "./static/Dairy and breakfast/Honey.jpeg",
  },
  {
    id: 49,
    title: "Jam",
    category: "Dairy & Breakfast",
    price: 25,
    image: "./static/Dairy and breakfast/Jam.jpeg",
  },
  {
    id: 50,
    title: "Kissan jam",
    category: "Dairy & Breakfast",
    price: 25,
    image: "./static/Dairy and breakfast/Kissan jam.jpeg",
  },
  {
    id: 51,
    title: "Tea",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/image/tea.jpg",
  },
  {
    id: 52,
    title: "Horlicks",
    category: "Dairy & Breakfast",
    price: 55,
    image: "./static/Dairy and breakfast/Horlicks.jpeg",
  },
  {
    id: 54,
    title: "Milkmade",
    category: "Dairy & Breakfast",
    price: 55,
    image: "./static/Dairy and breakfast/Milkmade.jpeg",
  },
  {
    id: 55,
    title: "Nescafe",
    category: "Dairy & Breakfast",
    price: 25,
    image: "./static/Dairy and breakfast/Nescafe.jpeg",
  },
  {
    id: 56,
    title: "Nut butter",
    category: "Dairy & Breakfast",
    price: 25,
    image: "./static/Dairy and breakfast/Nut butter.jpeg",
  },
  {
    id: 57,
    title: "Oatmeal",
    category: "Dairy & Breakfast",
    price: 75,
    image: "./static/Dairy and breakfast/Oatmeal.jpeg",
  },
  {
    id: 58,
    title: "Sweet yogurt",
    category: "Dairy & Breakfast",
    price: 75,
    image: "./static/Dairy and breakfast/Sweet Yogurt.jpeg",
  },
  {
    id: 59,
    title: "soup",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/Dairy and breakfast/Soap.jpeg",
  },
  {
    id: 60,
    title: "yippee",
    category: "Dairy & Breakfast",
    price: 50,
    image: "./static/Dairy and breakfast/yippe.jpeg",
  },
  {
    id: 61,
    title: "Rava dosa",
    category: "Dairy & Breakfast",
    price: 100,
    image: "./static/Dairy and breakfast/Rava dosa.jpeg",
  },
  {
    id: 62,
    title: "Quaker oat",
    category: "Dairy & Breakfast",
    price: 80,
    image: "./static/Dairy and breakfast/Quaker oat.jpeg",
  },
  {
    id: 63,
    title: "Maggie",
    category: "Dairy & Breakfast",
    price: 14,
    image: "./static/Dairy and breakfast/Maggie.jpeg",
  },
  {
    id: 64,
    title: "Naturalla",
    category: "Dairy & Breakfast",
    price: 30,
    image: "./static/Dairy and breakfast/Naturalla.jpeg",
  },
  {
    id: 65,
    title: "Patanjali jam",
    category: "Dairy & Breakfast",
    price: 30,
    image: "./static/Dairy and breakfast/Patanjali jam.jpeg",
  },
  {
    id: 66,
    title: "Mozzarellla cheese",
    category: "Dairy & Breakfast",
    price: 30,
    image: "./static/Dairy and breakfast/Mozzarellla cheese.jpeg",
  },
  {
    id: 67,
    title: "Bournvita",
    category: "Dairy & Breakfast",
    price: 100,
    image: "./static/Dairy and breakfast/Bournvita.jpeg",
  },

  {
    id: 69,
    title: "Peanuts smoot",
    category: "Dairy & Breakfast",
    price: 30,
    image: "./static/Dairy and breakfast/Peanuts smooth.jpeg",
  },
  {
    id: 70,
    title: "Band aid",
    category: "personal care",
    price: 45,
    image: "./static/personal care/Band aid.jpeg",
  },
  {
    id: 71,
    title: "Dove soap",
    category: "personal care",
    price: 50,
    image: "./static/personal care/Dove soap.jpeg",
  },
  {
    id: 72,
    title: "Dove body wash",
    category: "personal care",
    price: 80,
    image: "./static/personal care/Dove bodywash.jpeg",
  },
  {
    id: 73,
    title: "Face massager",
    category: "personal care",
    price: 30,
    image: "./static/personal care/face massager.jpeg",
  },
  {
    id: 74,
    title: "Facemask",
    category: "personal care",
    price: 100,
    image: "./static/personal care/Facemask.jpeg",
  },
  {
    id: 75,
    title: "Face rollon",
    category: "personal care",
    price: 100,
    image: "./static/personal care/Face rollon.jpeg",
  },
  {
    id: 76,
    title: "Foot peal mask",
    category: "personal care",
    price: 100,
    image: "./static/personal care/foot peal mask.jpeg",
  },
  {
    id: 77,
    title: "Garnier wipes",
    category: "personal care",
    price: 100,
    image: "./static/personal care/Garnier wipes.jpeg",
  },
  {
    id: 78,
    title: "Garnier cleansing",
    category: "personal care",
    price: 100,
    image: "./static/personal care/Garnier cleansing.jpeg",
  },
  {
    id: 79,
    title: "simple facewash",
    category: "personal care",
    price: 50,
    image: "./static/personal care/simple facewash.jpeg",
  },
  {
    id: 80,
    title: "Ponds powder",
    category: "personal care",
    price: 50,
    image: "./static/personal care/Ponds powder.jpeg",
  },
  {
    id: 81,
    title: "Dove room fresh",
    category: "personal care",
    price: 250,
    image: "./static/personal care/Dove room fresh.jpeg",
  },
  {
    id: 82,
    title: "Dove spray",
    category: "personal care",
    price: 150,
    image: "./static/personal care/Dove spray.jpeg",
  },
  {
    id: 83,
    title: "Whisper",
    category: "personal care",
    price: 60,
    image: "./static/personal care/Whisper.jpeg",
  },
  {
    id: 84,
    title: "Nivea set",
    category: "personal care",
    price: 200,
    image: "./static/personal care/Nivea set.jpeg",
  },
  {
    id: 85,
    title: "Tooth.brush",
    category: "personal care",
    price: 15,
    image: "./static/personal care/Tooth.brush.jpeg",
  },
  {
    id: 86,
    title: "Colgate",
    category: "personal care",
    price: 70,
    image: "./static/personal care/Colgate.jpeg",
  },
  {
    id: 87,
    title: "Colgate toothpast",
    category: "personal care",
    price: 70,
    image: "./static/personal care/Colgate toothpast.jpeg",
  },
  {
    id: 88,
    title: "Vaseline",
    category: "personal care",
    price: 30,
    image: "./static/personal care/Vaseline.jpeg",
  },
  {
    id: 89,
    title: "Vaseline jelly",
    category: "personal care",
    price: 30,
    image: "./static/personal care/Vaseline jelly.jpeg",
  },
  {
    id: 90,
    title: "Venus razor",
    category: "personal care",
    price: 30,
    image: "./static/personal care/Venus razor.jpeg",
  },
  {
    id: 91,
    title: "Venus razor",
    category: "personal care",
    price: 50,
    image: "./static/personal care/Venus razor.jpeg",
  },
  {
    id: 92,
    title: "Ponds sunscreen",
    category: "personal care",
    price: 200,
    image: "./static/personal care/Ponds sunscreen.jpeg",
  },
  {
    id: 93,
    title: "Pantene E",
    category: "personal care",
    price: 200,
    image: "./static/personal care/Pantene E.jpeg",
  },
  {
    id: 94,
    title: "Ponds 35+",
    category: "personal care",
    price: 150,
    image: "./static/personal care/Ponds 35+.jpeg",
  },
  {
    id: 95,
    title: "Lotus",
    category: "personal care",
    price: 200,
    image: "./static/personal care/Lotus.jpeg",
  },
  {
    id: 96,
    title: "Lotus whitecream",
    category: "personal care",
    price: 100,
    image: "./static/personal care/Lotus whitecream.jpeg",
  },
  {
    id: 97,
    title: "Mac primer",
    category: "personal care",
    price: 200,
    image: "./static/personal care/Mac primer.jpeg",
  },
  {
    id: 98,
    title: "Lakme primer",
    category: "personal care",
    price: 150,
    image: "./static/personal care/Lakme primer.jpeg",
  },
  {
    id: 99,
    title: "Lakme sunscreen",
    category: "personal care",
    price: 300,
    image: "./static/personal care/Lakme sunscreen.jpeg",
  },
  {
    id: 100,
    title: "Lakme 9to5",
    category: "personal care",
    price: 300,
    image: "./static/personal care/Lakme 9to5.jpeg",
  },
  {
    id: 101,
    title: "Lavender mask",
    category: "personal care",
    price: 200,
    image: "./static/personal care/lavender mask.jpeg",
  },
  {
    id: 102,
    title: "lorial kajal",
    category: "personal care",
    price: 200,
    image: "./static/personal care/lorial kajal.jpeg",
  },
  {
    id: 103,
    title: "Castor oil",
    category: "personal care",
    price: 150,
    image: "./static/personal care/Castor oil.jpeg",
  },
  {
    id: 104,
    title: "Mac Foundation",
    category: "personal care",
    price: 500,
    image: "./static/personal care/Mac foundation.jpeg",
  },
  {
    id: 105,
    title: "Moisturizer",
    category: "personal care",
    price: 120,
    image: "./static/personal care/moisturizer.jpeg",
  },
  {
    id: 106,
    title: "Kitkat",
    category: "Snacks and Beverages",
    price: 20,
    image: "./static/Snacks/kitkat.jpeg",
  },
  {
    id: 107,
    title: "Kurkure",
    category: "Snacks and Beverages",
    price: 20,
    image: "./static/Snacks/kurkure.jpeg",
  },
  {
    id: 108,
    title: "Oreo cone",
    category: "Snacks and Beverages",
    price: 25,
    image: "./static/Snacks/Oreo cone.jpeg",
  },
  {
    id: 109,
    title: "Bounty",
    category: "Snacks and Beverages",
    price: 25,
    image: "./static/Snacks/Bounty.jpeg",
  },
  {
    id: 110,
    title: "Cheetos",
    category: "Snacks and Beverages",
    price: 30,
    image: "./static/Snacks/Cheetos.jpeg",
  },
  {
    id: 111,
    title: "Chamallows",
    category: "Snacks and Beverages",
    price: 30,
    image: "./static/Snacks/Chamallows.jpeg",
  },
  {
    id: 112,
    title: "Coca cola tin",
    category: "Snacks and Beverages",
    price: 40,
    image: "./static/Snacks/Coca cola tin.jpeg",
  },
  {
    id: 113,
    title: "Cookie",
    category: "Snacks and Beverages",
    price: 40,
    image: "./static/Snacks/Cookie.jpg",
  },
  {
    id: 114,
    title: "Croissant",
    category: "Snacks and Beverages",
    price: 30,
    image: "./static/Snacks/Croissant.jpeg",
  },
  {
    id: 115,
    title: "Fanta",
    category: "Snacks and Beverages",
    price: 50,
    image: "./static/Snacks/Fanta.jpeg",
  },
  {
    id: 116,
    title: "Fanta tin",
    category: "Snacks and Beverages",
    price: 50,
    image: "./static/Snacks/Fanta tin.jpeg",
  },
  {
    id: 117,
    title: "Hersheys",
    category: "Snacks and Beverages",
    price: 40,
    image: "./static/Snacks/Hersheys.jpeg",
  },
  {
    id: 118,
    title: "kinder joy",
    category: "Snacks and Beverages",
    price: 50,
    image: "./static/Snacks/Kinder joy.jpeg",
  },
  {
    id: 119,
    title: "Kitkat cone",
    category: "Snacks and Beverages",
    price: 50,
    image: "./static/Snacks/Kitkat cone.jpeg",
  },
  {
    id: 120,
    title: "Lassi",
    category: "Snacks and Beverages",
    price: 30,
    image: "./static/Snacks/Lassi.jpeg",
  },
  // Baby Care (15 items)
  { id: 121, title: "Dove kit", price: 150, category: "Baby Care", image: "./static/Baby Care/Dove kit.jpeg" },
  { id: 122, title: "Huggies", price: 200, category: "Baby Care", image: "./static/Baby Care/Huggies.jpeg" },
  { id: 123, title: "Huggies wipes", price: 175, category: "Baby Care", image: "./static/Baby Care/Huggies wipes.jpeg" },
  { id: 124, title: "Johnsons kit", price: 300, category: "Baby Care", image: "./static/Baby Care/Johnsons kit.jpeg" },
  { id: 125, title: "Johnsons powder", price: 250, category: "Baby Care", image: "./static/Baby Care/Johnsons powder.jpeg" },
  { id: 126, title: "Johnsons Shampoo", price: 200, category: "Baby Care", image: "./static/Baby Care/Johnsons shampoo.jpeg" },
  { id: 127, title: "Johnsons shampoos", price: 400, category: "Baby Care", image: "./static/Baby Care/Johnsons shampoos.jpeg" },
  { id: 128, title: "Mamy poko pants", price: 200, category: "Baby Care", image: "./static/Baby Care/Mamy poko pants.jpeg" },
  { id: 129, title: "Mamy poko pants l", price: 200, category: "Baby Care", image: "./static/Baby Care/Mamy poko pants l.jpeg" },
  { id: 130, title: "Mamy poko pants s4", price: 200, category: "Baby Care", image: "./static/Baby Care/Mamy poko pants s4.jpeg" },
  { id: 131, title: "Pampers", price: 200, category: "Baby Care", image: "./static/Baby Care/Pampers.jpeg" },
  { id: 132, title: "Pampers wipes", price: 200, category: "Baby Care", image: "./static/Baby Care/Pampers wipes.jpeg" },
  { id: 133, title: "Baby biscuits", price: 75, category: "Baby Care", image: "./static/Baby Care/Baby biscuits.jpeg" },
  { id: 134, title: "Nestle cereales", price: 300, category: "Baby Care", image: "./static/Baby Care/Nestle cereales.jpeg" },

  // Grocery (40 items)
  { id: 135, title: "Jeera powder", price: 250, category: "Grocery", image: "./static/Grocery/Jeera powder.jpeg" },
  { id: 136, title: "Kasuri methi", price: 250, category: "Grocery", image: "./static/Grocery/Kasuri methi.jpeg" },
  { id: 137, title: "Green moong", price: 250, category: "Grocery", image: "./static/Grocery/Green moong.jpeg" },
  { id: 138, title: "Clove", price: 70, category: "Grocery", image: "./static/Grocery/Clove.jpeg" },
  { id: 139, title: "Chakki atta", price: 300, category: "Grocery", image: "./static/Grocery/Chakki atta.jpeg" },
  { id: 140, title: "Ragi flour", price: 300, category: "Grocery", image: "./static/Grocery/Ragi flour.jpeg" },
  { id: 141, title: "Jasmine rice", price: 300, category: "Grocery", image: "./static/Grocery/Jasmine rice.jpeg" },
  { id: 142, title: "Basmathi rice", price: 300, category: "Grocery", image: "./static/Grocery/Basmathi rice.jpeg" },
  { id: 143, title: "Masala vadamix", price: 250, category: "Grocery", image: "./static/Grocery/Masala vadamix.jpeg" },
  { id: 144, title: "Black seeds", price: 70, category: "Grocery", image: "./static/Grocery/Black seeds.jpeg" },
  { id: 145, title: "Mutton masala", price: 50, category: "Grocery", image: "./static/Grocery/Mutton masala.jpeg" },
  { id: 146, title: "Sugar", price: 150, category: "Grocery", image: "./static/Grocery/Sugar.jpeg" },
  { id: 147, title: "Salt", price: 150, category: "Grocery", image: "./static/Grocery/Salt.jpeg" },
  { id: 148, title: "Aashirvad salt", price: 150, category: "Grocery", image: "./static/Grocery/Aashirvad salt.jpeg" },
  { id: 149, title: "Kasoori methi", price: 150, category: "Grocery", image: "./static/Grocery/Kasoori methi.jpeg" },
  { id: 150, title: "Green cardomom", price: 250, category: "Grocery", image: "./static/Grocery/Green cardomom.jpeg" },
  { id: 151, title: "Cardomom", price: 250, category: "Grocery", image: "./static/Grocery/Cardomom.jpeg" },
  { id: 152, title: "Cardomom pods", price: 250, category: "Grocery", image: "./static/Grocery/Cardomom pods.jpeg" },
  { id: 153, title: "Coriander powder", price: 250, category: "Grocery", image: "./static/Grocery/Coriander powder.jpeg" },
  { id: 154, title: "Besan", price: 150, category: "Grocery", image: "./static/Grocery/Besan.jpeg" },
  { id: 155, title: "Masoor dal", price: 150, category: "Grocery", image: "./static/Grocery/Masoor dal.jpeg" },
  { id: 156, title: "Organic kalonji", price: 300, category: "Grocery", image: "./static/Grocery/Organic kalonji.jpeg" },
  { id: 157, title: "Cumin ground 180g", price: 300, category: "Grocery", image: "./static/Grocery/Cumin ground 180g.jpeg" },
  { id: 158, title: "Moong dal", price: 300, category: "Grocery", image: "./static/Grocery/Moong dal.jpeg" },
  { id: 159, title: "Cardomom seeds", price: 170, category: "Grocery", image: "./static/Grocery/Cardomom seeds.jpeg" },
  { id: 160, title: "Cardomom seeds 50g", price: 80, category: "Grocery", image: "./static/Grocery/Cardomom seeds 50g.jpeg" },
  { id: 161, title: "Atta", price: 280, category: "Grocery", image: "./static/Grocery/Atta.jpeg" },
  { id: 162, title: "Ground cumin", price: 150, category: "Grocery", image: "./static/Grocery/Ground cumin.jpeg" },
  { id: 163, title: "Biryani masala", price: 150, category: "Grocery", image: "./static/Grocery/Biryani masala.jpeg" },
  { id: 164, title: "Sticky rice", price: 350, category: "Grocery", image: "./static/Grocery/Sticky rice.jpeg" },
  { id: 165, title: "Sweet rice", price: 200, category: "Grocery", image: "./static/Grocery/Sweet rice.jpeg" },
  { id: 166, title: "Toor dal", price: 200, category: "Grocery", image: "./static/Grocery/Toor dal.jpeg" },
  { id: 167, title: "Tata chanadal", price: 200, category: "Grocery", image: "./static/Grocery/Tata chanadal.jpeg" },
  { id: 168, title: "Fish curry masala", price: 200, category: "Grocery", image: "./static/Grocery/Fish curry masala.jpeg" },
  { id: 169, title: "Dal tadka", price: 200, category: "Grocery", image: "./static/Grocery/Dal tadka.jpeg" },
  { id: 170, title: "Garam masala", price: 60, category: "Grocery", image: "./static/Grocery/Garam masala.jpeg" },
  { id: 171, title: "organic moong dal", price: 100, category: "Grocery", image: "./static/Grocery/organic moong dal.jpeg" },
  { id: 172, title: "Pickle", price: 100, category: "Grocery", image: "./static/Grocery/Pickle.jpeg" },
  { id: 173, title: "Pizza sause", price: 100, category: "Grocery", image: "./static/Grocery/Pizza sause.jpeg" },
  { id: 174, title: "Rice", price: 300, category: "Grocery", image: "./static/Grocery/Rice.jpeg" },
  { id: 175, title: "Natco rice flour", price: 300, category: "Grocery", image: "./static/Grocery/Natco rice flour.jpeg" },
  { id: 176, title: "Urad dal", price: 100, category: "Grocery", image: "./static/Grocery/Urad dal.jpeg" },
  { id: 177, title: "Multigrain atta", price: 400, category: "Grocery", image: "./static/Grocery/Multigrain atta.jpeg" },

  // House Hold (31 items)
  { id: 178, title: "Aer", price: 120, category: "House Hold", image: "./static/household/Aer.jpeg" },
  { id: 179, title: "Air fresher", price: 120, category: "House Hold", image: "./static/household/Air fresher.jpeg" },
  { id: 180, title: "Air mist", price: 100, category: "House Hold", image: "./static/household/Air mist.jpeg" },
  { id: 181, title: "Air wick", price: 100, category: "House Hold", image: "./static/household/Air wick.jpeg" },
  { id: 182, title: "aireal", price: 200, category: "House Hold", image: "./static/household/aireal.jpeg" },
  { id: 183, title: "Attack", price: 200, category: "House Hold", image: "./static/household/Attack.jpeg" },
  { id: 184, title: "Clip", price: 60, category: "House Hold", image: "./static/household/clip.jpeg" },
  { id: 185, title: "clorox", price: 60, category: "House Hold", image: "./static/household/clorox.jpeg" },
  { id: 186, title: "dettol", price: 50, category: "House Hold", image: "./static/household/dettol.jpeg" },
  { id: 187, title: "dishwasher", price: 100, category: "House Hold", image: "./static/household/dishwasher.jpeg" },
  { id: 188, title: "downy", price: 100, category: "House Hold", image: "./static/household/downy.jpeg" },
  { id: 189, title: "Downy cleaner", price: 100, category: "House Hold", image: "./static/household/Downy cleaner.jpeg" },
  { id: 190, title: "dust pan", price: 80, category: "House Hold", image: "./static/household/dust pan.jpeg" },
  { id: 191, title: "dustbin", price: 80, category: "House Hold", image: "./static/household/dustbin.jpeg" },
  { id: 192, title: "dustbin cover", price: 80, category: "House Hold", image: "./static/household/dustbin cover.jpeg" },
  { id: 193, title: "Febreze", price: 80, category: "House Hold", image: "./static/household/Febreze.jpeg" },
  { id: 194, title: "Fairy", price: 90, category: "House Hold", image: "./static/household/Fairy.jpeg" },
  { id: 195, title: "Glade", price: 100, category: "House Hold", image: "./static/household/Glade.jpeg" },
  { id: 196, title: "Glade spray", price: 100, category: "House Hold", image: "./static/household/Glade spray.jpeg" },
  { id: 197, title: "Glade air", price: 100, category: "House Hold", image: "./static/household/Glade air fresher.jpeg" },
  { id: 198, title: "Glat set", price: 100, category: "House Hold", image: "./static/household/Glat set.jpeg" },
  { id: 199, title: "Harpic", price: 300, category: "House Hold", image: "./static/household/Harpic.jpeg" },
  { id: 200, title: "Lenor", price: 150, category: "House Hold", image: "./static/household/Lenor.jpeg" },
  { id: 201, title: "mop", price: 150, category: "House Hold", image: "./static/household/mop.jpeg" },
  { id: 202, title: "Pril", price: 150, category: "House Hold", image: "./static/household/Pril.jpeg" },
  { id: 203, title: "Room spray", price: 230, category: "House Hold", image: "./static/household/Room spray.jpeg" },
  { id: 204, title: "Softouch", price: 250, category: "House Hold", image: "./static/household/Softouch.jpeg" },
  { id: 205, title: "sponge", price: 400, category: "House Hold", image: "./static/household/sponge.jpeg" },
  { id: 206, title: "spray bottles", price: 400, category: "House Hold", image: "./static/household/spray bottles.jpeg" },
  { id: 207, title: "Tide", price: 240, category: "House Hold", image: "./static/household/tide.jpeg" },
  { id: 208, title: "Tub", price: 270, category: "House Hold", image: "./static/household/tub.jpeg" },
  { id: 209, title: "Vanish", price: 300, category: "House Hold", image: "./static/household/Vanish.jpeg" },

  // Home and Kitchen (14 items)
  { id: 210, title: "Apron", price: 275, category: "Home and Kitchen", image: "./static/kitchen/Apron.jpeg" },
  { id: 211, title: "Boul set", price: 320, category: "Home and Kitchen", image: "./static/kitchen/Boul set.jpeg" },
  { id: 212, title: "Chopper", price: 250, category: "Home and Kitchen", image: "./static/kitchen/Chopper.jpeg" },
  { id: 213, title: "Container", price: 200, category: "Home and Kitchen", image: "./static/kitchen/Container.jpeg" },
  { id: 214, title: "Crocy holder", price: 200, category: "Home and Kitchen", image: "./static/kitchen/Crocy holder.jpeg" },
  { id: 215, title: "Cutter", price: 200, category: "Home and Kitchen", image: "./static/kitchen/Cutter.jpeg" },
  { id: 216, title: "Cutting board", price: 200, category: "Home and Kitchen", image: "./static/kitchen/Cutting board.jpeg" },
  { id: 217, title: "Glass set", price: 150, category: "Home and Kitchen", image: "./static/kitchen/Glass set.jpeg" },
  { id: 218, title: "Grain container", price: 150, category: "Home and Kitchen", image: "./static/kitchen/Grain container.jpeg" },
  { id: 219, title: "Jar", price: 150, category: "Home and Kitchen", image: "./static/kitchen/Jar.jpeg" },
  { id: 220, title: "Knife holder", price: 150, category: "Home and Kitchen", image: "./static/kitchen/Knife holder.jpeg" },
  { id: 221, title: "Plate set", price: 400, category: "Home and Kitchen", image: "./static/kitchen/Plate set.jpeg" },
  { id: 222, title: "Round pan", price: 400, category: "Home and Kitchen", image: "./static/kitchen/Round pan.jpeg" },
  { id: 223, title: "Spice holder", price: 400, category: "Home and Kitchen", image: "./static/kitchen/Spice holder.jpeg" }
];
